package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQ, PARENTESIS_DER, LLAVES, PUNTO, COMA, OPERADORES_RELACIONALES, DESCONOCIDO
}