package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQ, PARENTESIS_DER, LLAVES, PUNTO, COMA, OPERADORES_RELACIONALES, DESCONOCIDO, PALABRA_RESERVADA_ENTERO, PALABRA_RESERVADA_DECIMAL,
    PALABRA_RESERVADA_CADENA, PALABRA_RESERVADA_CARACTER, PALABRA_RESERVADA_FOR, PALABRA_RESERVADA_WHILE, PALABRA_RESERVADA_DO, PALABRA_RESERVADA_SI,
    PALABRA_RESERVADA_ELSE, PALABRA_RESERVADA_SWITCH, PALABRA_RESERVADA_CASO, PALABRA_RESERVADA_MAIN, COMENTARIODELINEA, COMENTARIODEBLOQUE, CADENA, CARACTER, LLAVE_IZQ, LLAVE_DER, CORCHETE_IZQ, CORCHETE_DER,
    FINDESENTENCIA, DOSPUNTOS, OPERADOR_ASIGNACION, OPERADOR_INCREMENTO, OPERADOR_DECREMENTO, PRINCIPAL, BUCLE, CONDICIONAL, METODO, CLASE, PALABRA_RESERVADA

}